<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ffmpeg.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScreenLapse.Lib\ScreenLapse.Lib.csproj" />
  </ItemGroup>

</Project>